version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
       - "9092:9092"
    restart: always
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        # 🔥 FIX STARTS HERE
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        # 🔥 FIX ENDS HERE

        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    volumes:
        - kafka_data:/var/lib/kafka/data
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres-keycloak
  authservice:
    build: ./AuthService/AuthService/AuthService
    container_name: auth_service
    depends_on:
      - mysql
      - kafka
      - keycloak
    ports:
      - "8086:8086"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KEYCLOAK_SERVER_URL: http://keycloak:8080
  userservice:
    build: ./UserService/UserService/UserService
    container_name: user_service
    depends_on:
      - mysql
      - kafka
      - keycloak
    ports:
      - "8087:8087"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KEYCLOAK_SERVER_URL: http://keycloak:8080
  jobservice:
    build: ./JobService/JobService/JobService
    container_name: job_service
    depends_on:
      - mysql
      - kafka
      - keycloak
    ports:
      - "8088:8088"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KEYCLOAK_SERVER_URL: http://keycloak:8080

  applicationservice:
    build: ./ApplicationService/ApplicationsService/ApplicationsService
    container_name: application_service
    depends_on:
      - mysql
      - kafka
      - keycloak
    ports:
      - "8089:8089"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KEYCLOAK_SERVER_URL: http://keycloak:8080
  notificationservice:
    build: ./NotificationService/NotificationService/NotificationService
    container_name: notification_service
    depends_on:
      - mysql
      - kafka
      - keycloak
    ports:
      - "8090:8090"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  kong:
    image: kong:3.6
    container_name: kong
    restart: always
    ports:
      - "8000:8000"   # public API
      - "8001:8001"   # admin API
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./kong.yml:/kong/kong.yml
volumes:
  kafka_data:
  mysql_data:
  keycloak_data:
  zookeeper_data: