plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Kafka
	implementation 'org.springframework.kafka:spring-kafka'
	// Security (for JWT validation later)
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// OAuth2 Resource Server (to validate Keycloak tokens)
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

	// Keycloak Admin Client (VERY IMPORTANT)
	implementation 'org.keycloak:keycloak-admin-client:24.0.3'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// Dev tools
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
tasks.named('test') {
	useJUnitPlatform()
}
